added calendar
js-tasks-ru/htmlcss-20230530_el-classico pull request #10
Opened 2023-06-15 14:26 UTC by elclass1co

2023-06-15 14:27 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-15 20:32 UTC, GSemikozov requested changes

2023-06-15 20:32 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
`28 26 32`

2023-06-15 20:32 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding-bottom: 24px;
margin-bottom

2023-06-19 21:00 UTC, GSemikozov approved these changes

2023-06-19 21:00 UTC, merged