added modal
js-tasks-ru/htmlcss-20230530_el-classico pull request #11
Opened 2023-06-19 07:40 UTC by elclass1co

2023-06-19 07:46 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-19 07:49 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 07:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 08:05 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-19 21:02 UTC, GSemikozov requested changes

2023-06-19 21:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: absolute;
принципиально fixed

2023-06-19 21:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  position: fixed;
а тут absolute)

2023-06-19 21:02 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 40%;
50?

2023-06-21 01:28 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-06-23 03:48 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-23 04:14 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-06-23 04:15 UTC, elclass1co commented on 05-lection3/02-modal/modal.css
> +  top: 40%;
Все исправил. По поводу 40%, читал статью про модалки, и там было сказано, что удобно если модалка удалена на 40% от верхнего края

2023-06-23 14:15 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +  top: 40%;
нет, наша задача - разместить модалку по центру

2023-06-23 14:15 UTC, GSemikozov approved these changes

2023-06-23 14:15 UTC, merged