add input area
js-tasks-ru/htmlcss-20230530_el-classico pull request #21
Opened 2023-07-09 05:37 UTC by elclass1co

Добавил input area. SVG иконки пока вставил в html, спрайты еще не смержились)

2023-07-09 05:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-07-09 05:39 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-07-09 23:20 UTC, GSemikozov requested changes

2023-07-09 23:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-field__input_success{
.text-field_success .text-field__input {}

2023-07-09 23:20 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +.text-field__input_error{
см выше

2023-08-06 06:27 UTC, GSemikozov approved these changes

2023-08-06 06:27 UTC, merged